In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [9]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep = ';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10003    PREGO  BT10    100    100  z0019_2.csv 2025-04-18 23:26:37.584638
1  10005  MACHADO  BT50    500    500  z0019_2.csv 2025-04-18 23:26:37.584638
2  10006    SERRA  BT60    600    600  z0019_2.csv 2025-04-18 23:26:37.584638

In [10]:
con.execute("""
            CREATE TABLE IF NOT EXISTS  bronze_produtos(
                NATBR VARCHAR,
                MAKTX VARCHAR,
                WERKS VARCHAR,
                MAINST VARCHAR,
                LABST VARCHAR,
                nome_arquivo VARCHAR,
                data_ingestao TIMESTAMP
            )
""")

In [11]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [15]:
resultado = con.execute("SELECT * FROM bronze_produtos").fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINST LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100   100  z0019_1.csv 2025-04-18 23:25:06.233833
1  10002   MARTELO  BT20    200   200  z0019_1.csv 2025-04-18 23:25:06.233833
2  10003     PREGO  BT30    300   300  z0019_1.csv 2025-04-18 23:25:06.233833
3  10003     PREGO  BT10    100   100  z0019_2.csv 2025-04-18 23:26:37.584638
4  10005   MACHADO  BT50    500   500  z0019_2.csv 2025-04-18 23:26:37.584638

In [17]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z00190")